# http://about.travis-ci.org/docs/user/languages/python/

sudo: false
language: python
python:
  - "2.6"
  - "2.7"

install: 
  - python setup.py install
  - pip install coverage coveralls

script: 
  - coverage run --source=mwclient setup.py test

after_success:
  - coveralls
