# http://about.travis-ci.org/docs/user/languages/python/

language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"

install: 
  - python setup.py install

before_script:
  - pip install -r requirements-dev.txt

script: 
  - py.test --pep8 mwclient -v tests/client_test.py
